package io.sicredi.aberturadecontaslegadooriginacao.entities;

public enum EtapaProcessoOriginacao {
    ACQUISITION_ORDER, ACQUISITION_ORDER_CARTEIRA, CUSTOMER_DATA, REGISTER_DATA, GESTENT, PRODUCT_CAPITAL_LEGACY, PRODUCT_ACCOUNT_LEGACY,PRODUCT_INVESTMENT_LEGACY, ORIGINACAO_LEGADO,
}
