<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N2:definitions targetNamespace="http://www.sicredi.com.br/mua/cadastro/business/server/ws/v1/ContaSalarioService" xmlns:WL5G3N0="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:WL5G3N1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N3="http://www.sicredi.com.br/mua/cadastro/business/server/ws/v1/ContaSalarioService" xmlns:WL5G3N4="http://sicredi.com.br/arqref/exception/binding/" xmlns:WL5G3N5="http://schemas.xmlsoap.org/wsdl/soap/">
<WL5G3N0:Policy WL5G3N1:Id="ContaSalarioServicePortBinding_WSAT_policy">
<WL5G3N0:ExactlyOne>
<WL5G3N0:All>
<wsat:ATAssertion wsp:Optional="true" xmlns:wsat="http://schemas.xmlsoap.org/ws/2004/10/wsat" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"/>
</WL5G3N0:All>
<WL5G3N0:All>
<wsat12:ATAssertion wsp:Optional="true" xmlns:wsat12="http://docs.oasis-open.org/ws-tx/wsat/2006/06" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"/>
</WL5G3N0:All>
<WL5G3N0:All>
<wsat12:ATAssertion wsp:Optional="true" xmlns:wsat12="http://docs.oasis-open.org/ws-tx/wsat/2006/06" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"/>
</WL5G3N0:All>
</WL5G3N0:ExactlyOne>
</WL5G3N0:Policy>
    <WL5G3N2:types>
        <xsd:schema xmlns:WL5G3N2="http://www.w3.org/ns/ws-policy" xmlns:WL5G3N3="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N4="http://www.sicredi.com.br/mua/cadastro/business/server/ws/v1/ContaSalarioService" xmlns:WL5G3N5="http://sicredi.com.br/arqref/exception/binding/" xmlns:WL5G3N6="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:seb="http://sicredi.com.br/arqref/exception/binding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.sicredi.com.br/mua/cadastro/business/server/ws/v1/ContaSalarioService" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wssutil="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.sicredi.com.br/mua/cadastro/business/server/ws/v1/ContaSalarioService" schemaLocation="http://osb3cmua.hom.sicredi.net/osb-cadastro/contas/contaSalario/ws/v1/ps/ContaSalarioService?SCHEMA%2Fosb-cadastro%2Fcontas%2FcontaSalario%2Fws%2Fv1%2Fps%2Fwsdl%2FContaSalarioService"/>
            <xsd:import namespace="http://sicredi.com.br/arqref/exception/binding/" schemaLocation="http://osb3cmua.hom.sicredi.net:80/osb-cadastro/contas/contaSalario/ws/v1/ps/ContaSalarioService?SCHEMA%2Fosb-cadastro%2Farqref%2Fexception%2Fbinding%2FServException"/>
        </xsd:schema>
    </WL5G3N2:types>
    <WL5G3N2:message name="criarContaSalario">
        <WL5G3N2:part name="parameters" element="WL5G3N3:criarContaSalario"/>
    </WL5G3N2:message>
    <WL5G3N2:message name="criarContaSalarioResponse">
        <WL5G3N2:part name="parameters" element="WL5G3N3:criarContaSalarioResponse"/>
    </WL5G3N2:message>
    <WL5G3N2:message name="ServException">
        <WL5G3N2:part name="fault" element="WL5G3N4:ServException"/>
    </WL5G3N2:message>
    <WL5G3N2:portType name="ContaSalarioServices">
        <WL5G3N2:operation name="criarContaSalario">
            <WL5G3N2:input message="WL5G3N3:criarContaSalario"/>
            <WL5G3N2:output message="WL5G3N3:criarContaSalarioResponse"/>
            <WL5G3N2:fault name="ServException" message="WL5G3N3:ServException"/>
        </WL5G3N2:operation>
    </WL5G3N2:portType>
    <WL5G3N2:binding name="ContaSalarioServicePortBinding" type="WL5G3N3:ContaSalarioServices">
        <WL5G3N5:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <WL5G3N2:operation name="criarContaSalario">
<WL5G3N0:Policy>
<WL5G3N0:PolicyReference URI="#ContaSalarioServicePortBinding_WSAT_policy"/>
</WL5G3N0:Policy>
            <WL5G3N5:operation/>
            <WL5G3N2:input>
                <WL5G3N5:body use="literal"/>
            </WL5G3N2:input>
            <WL5G3N2:output>
                <WL5G3N5:body use="literal"/>
            </WL5G3N2:output>
            <WL5G3N2:fault name="ServException">
                <WL5G3N5:fault name="ServException" use="literal"/>
            </WL5G3N2:fault>
        </WL5G3N2:operation>
    </WL5G3N2:binding>
    <WL5G3N2:service name="ContaSalarioServicePortBindingQSService">
        <WL5G3N2:documentation>OSB Service</WL5G3N2:documentation>
        <WL5G3N2:port name="ContaSalarioServicePortBindingQSPort" binding="WL5G3N3:ContaSalarioServicePortBinding">
            <WL5G3N5:address location="http://osb3cmua.hom.sicredi.net:80/osb-cadastro/contas/contaSalario/ws/v1/ps/ContaSalarioService"/>
        </WL5G3N2:port>
    </WL5G3N2:service>
</WL5G3N2:definitions>