package io.sicredi.aberturadecontaslegadooriginacao.dto;

public enum StatusProduto {
    STARTED("INICIADO"),
    WAITING_FORMALIZATION("AGUARDANDO_FORMALIZACAO"),
    WAITING_DEPENDENCIES("AGUARDANDO_DEPENDENCIAS"),
    WAITING_PRODUCT_AUTHORIZATION("AGUARDANDO_AUTORIZACAO_PRODUTO"),
    PENDING("PENDENTE"),
    CANCELLED("CANCELADO"),
    PROCESSING("PROCESSANDO"),
    RELEASING("LIBERANDO"),
    FINISHED("FINALIZADO"),
    RELEASED("LIBERADO"),
    WAITING_CUSTOMIZATION("AGUARDANDO_CUSTOMIZACAO"),
    WAITING_FRAUD_ANALYSIS("AGUARDANDO_ANALISE_SEGURANCA"),
    WAITING_MANUAL_RELEASE("AGUARDANDO_LIBERACAO_MANUAL"),
    WAITING_MEMBERSHIP("AGUARDANDO_INTEGRALIZACAO"),
    WAITING_RFB_ANALYSIS("AGUARDANDO_ANALISE_RFB"),
    WAITING_BACKOFFICE_ANALYSIS("AGUARDANDO_ANALISE_BACKOFFICE"),
    WAITING_BATCH_ENROLLMENT("AGUARDANDO_MATRICULA_EM_LOTE");

    private final String descricao;

    StatusProduto(String descricao) {
        this.descricao = descricao;
    }

    public String getDescricao() {
        return descricao;
    }
}
